version: '3.8'
services:
  db:
    container_name: database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'playgroundDb'
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db-data:
    external: false